import type { Metadata } from 'next'
import './globals.css'
import Script from 'next/script'


interface LayoutProps {
	children: React.ReactNode
}

const Layout = ({ children }: LayoutProps) => {
	return (
		<html lang='en' className='dark'>
			<body>{children}</body>
			<Script src='https://unpkg.com/tailwindcss-intersect@1.x.x/dist/observer.min.js' />
		</html>
	)
}

export default Layout

// → metadata

export const metadata: Metadata = {
	title: 'ExtractHub',
	description: 'Generated by create next app',
}
