import type { Metadata } from 'next'
import './globals.css'

interface LayoutProps {
	children: React.ReactNode
}

const Layout = ({ children }: LayoutProps) => {
	return (
		<html lang='en' className='dark'>
			<body>{children}</body>
		</html>
	)
}

export default Layout

// → metadata

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
